# Generated by Django 6.0.6 on 2026-06-17 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='room_levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='techsupport.levels'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='room_entities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='techsupport.entities'),
        ),
    ]
