# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0002_alter_entities_room_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='techsupport.ticket'),
        ),
    ]
