# Generated by Django 6.0.6 on 2026-06-19 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0003_alter_comment_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='techsupport.ticket'),
        ),
    ]
