# Generated by Django 6.0.6 on 2026-07-02 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0004_alter_comment_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('ALT', 'Alta'), ('MDA', 'Média'), ('BAI', 'Baixa')], default='MDA', max_length=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ABT', 'Aberto'), ('FCD', 'Fechado'), ('EA', 'Em Andamento'), ('CNL', 'Cancelado')], default='EA', max_length=3),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
