# Generated by Django 6.0.6 on 2026-07-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0005_alter_ticket_assigned_to_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MÉDIA', 'Média'), ('BAIXA', 'Baixa')], default='MÉDIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('EM ANDAMENTO', 'Em Andamento'), ('CANCELADO', 'Cancelado')], default='EM ANDAMENTO', max_length=20),
        ),
    ]
